export const HOME_CONTENT_KEYS = {
  HEADER_TITLE: "driver-app-home-header-title",
  STATUS_OFFLINE: "driver-app-home-status-offline",
  STATUS_ONLINE: "driver-app-home-status-online",
  ALERT_ACTIVE_RIDE_TITLE: "driver-app-home-alert-active-ride-title",
  ALERT_ACTIVE_RIDE_MESSAGE: "driver-app-home-alert-active-ride-message",
  ALERT_OK: "driver-app-home-alert-ok",
  TOAST_OFFER_TYPES_SAVED: "driver-app-home-toast-offer-types-saved",
  TOAST_OFFER_TYPES_FAILED: "driver-app-home-toast-offer-types-failed",
  TOAST_NOW_ONLINE: "driver-app-home-toast-now-online",
  TOAST_GO_ONLINE_FAILED: "driver-app-home-toast-go-online-failed",
  TOAST_STATUS_ONLINE_FAILED: "driver-app-home-toast-status-online-failed",
  TOAST_NOW_OFFLINE: "driver-app-home-toast-now-offline",
  TOAST_GO_OFFLINE_FAILED: "driver-app-home-toast-go-offline-failed",
  TOAST_STATUS_OFFLINE_FAILED: "driver-app-home-toast-status-offline-failed",
  SHEET_OFFER_TYPE_TITLE: "driver-app-home-sheet-offer-type-title",
  SHEET_OFFER_TYPE_ECONOMY: "driver-app-home-sheet-offer-type-economy",
  SHEET_OFFER_TYPE_SEDAN: "driver-app-home-sheet-offer-type-sedan",
  SHEET_OFFER_TYPE_SUV: "driver-app-home-sheet-offer-type-suv",
  SHEET_OFFER_TYPE_LUXURY: "driver-app-home-sheet-offer-type-luxury",
  SHEET_OFFER_TYPE_SAVING: "driver-app-home-sheet-offer-type-saving",
  SHEET_OFFER_TYPE_SAVE: "driver-app-home-sheet-offer-type-save",
  SHEET_SORT_TITLE: "driver-app-home-sheet-sort-title",
  SHEET_SORT_PICKUP_TIME: "driver-app-home-sheet-sort-pickup-time",
  SHEET_SORT_PICKUP_DISTANCE: "driver-app-home-sheet-sort-pickup-distance",
  SHEET_SORT_RESET: "driver-app-home-sheet-sort-reset",
  SHEET_SORT_APPLY: "driver-app-home-sheet-sort-apply",
  // Mute Notifications sheet
  SHEET_MUTE_TITLE: "driver-app-home-sheet-mute-title",
  SHEET_MUTE_JOB_OFFERS: "driver-app-home-sheet-mute-job-offers",
  SHEET_MUTE_ALL: "driver-app-home-sheet-mute-all",
  SHEET_MUTE_SAVE: "driver-app-home-sheet-mute-save",
  TOAST_MUTE_ALL: "driver-app-home-toast-mute-all",
  TOAST_MUTE_JOB_OFFERS: "driver-app-home-toast-mute-job-offers",
  TOAST_MUTE_SETTINGS_SAVED: "driver-app-home-toast-mute-settings-saved",
} as const;
