export const MORE_CONTENT_KEYS = {
  HEADER_TITLE: "driver-app-more-header-title",
  ITEM_PROFILE: "driver-app-more-item-profile",
  ITEM_INBOX: "driver-app-more-item-inbox",
  ITEM_CONTACT_BASE: "driver-app-more-item-contact-base",
  ITEM_SHARE_APP: "driver-app-more-item-share-app",
  ITEM_APP_SETTINGS: "driver-app-more-item-app-settings",
  ITEM_DELETE_PROFILE: "driver-app-more-item-delete-profile",
  ITEM_CHANGE_PASSWORD: "driver-app-more-item-change-password",
  ITEM_LOGOUT: "driver-app-more-item-logout",
  LOGOUT_CONFIRM_TITLE: "driver-app-more-logout-confirm-title",
  LOGOUT_CONFIRM_DESCRIPTION: "driver-app-more-logout-confirm-description",
  LOGOUT_CONFIRM_CANCEL: "driver-app-more-logout-confirm-cancel",
  LOGOUT_CONFIRM_CONFIRM: "driver-app-more-logout-confirm-confirm",
  DELETE_CONFIRM_TITLE: "driver-app-more-delete-confirm-title",
  DELETE_CONFIRM_DESCRIPTION: "driver-app-more-delete-confirm-description",
  DELETE_CONFIRM_CANCEL: "driver-app-more-delete-confirm-cancel",
  DELETE_CONFIRM_CONFIRM: "driver-app-more-delete-confirm-confirm",
  CONTACT_SHEET_TITLE: "driver-app-more-contact-sheet-title",
  CONTACT_LOADING: "driver-app-more-contact-loading",
  CONTACT_EMPTY: "driver-app-more-contact-empty",
  CONTACT_DRIVER_RELATIONS: "driver-app-more-contact-driver-relations",
  CONTACT_DISPATCHER: "driver-app-more-contact-dispatcher",
  CONTACT_CALL_DISPATCHER: "driver-app-more-contact-call-dispatcher",
  SHARE_TITLE: "driver-app-more-share-title",
  SHARE_MESSAGE: "driver-app-more-share-message",
  /** Web portal quick access (driver-web routes) */
  WEB_PORTAL_BANK_DEPOSITS: "driver-app-more-web-portal-bank-deposits-link-label",
  WEB_PORTAL_CHANGE_DEPOSIT_INFO: "driver-app-more-web-portal-change-deposit-info-link-label",
  WEB_PORTAL_EXPENSES: "driver-app-more-web-portal-expenses-link-label",
  WEB_PORTAL_REQUEST_CHARGES: "driver-app-more-web-portal-request-charges-link-label",
  WEB_PORTAL_MY_FLEETS: "driver-app-more-web-portal-my-fleets-link-label",
  WEB_PORTAL_RATINGS: "driver-app-more-web-portal-ratings-link-label",
  WEB_PORTAL_REPORT_ISSUE: "driver-app-more-web-portal-report-issue-link-label",
  WEB_PORTAL_MOVE_TO_WEB: "driver-app-more-web-portal-move-to-web-link-label",
} as const;
