export const ACTIVE_RIDE_CONTENT_KEYS = {
  HEADER_TITLE: "driver-app-active-ride-header-title",
  HEADER_EN_ROUTE: "driver-app-active-ride-header-en-route",
  HEADER_ON_SCENE: "driver-app-active-ride-header-on-scene",
  HEADER_LOADED: "driver-app-active-ride-header-loaded",
  HEADER_STOP: "driver-app-active-ride-header-stop",
  HEADER_COMPLETED: "driver-app-active-ride-header-completed",
  TOGGLE_MAP: "driver-app-active-ride-toggle-map",
  TOGGLE_DETAILS: "driver-app-active-ride-toggle-details",
  LOADING_TRIP: "driver-app-active-ride-loading-trip",
  LOADING_ADDRESS: "driver-app-active-ride-loading-address",
  ERROR_TITLE: "driver-app-active-ride-error-title",
  ERROR_MESSAGE: "driver-app-active-ride-error-message",
  ERROR_RETRY: "driver-app-active-ride-error-retry",
  COMPLETION_LOADING: "driver-app-active-ride-completion-loading",
  COMPLETION_SUBTEXT: "driver-app-active-ride-completion-subtext",
  SWIPE_MARK_ARRIVED: "driver-app-active-ride-swipe-mark-arrived",
  SWIPE_START_RIDE: "driver-app-active-ride-swipe-start-ride",
  SWIPE_COMPLETE_RIDE: "driver-app-active-ride-swipe-complete-ride",
  SWIPE_RESTART_RIDE: "driver-app-active-ride-swipe-restart-ride",
  SWIPE_PROCESSING: "driver-app-active-ride-swipe-processing",
  TOAST_CIRCLING_NOTIFIED: "driver-app-active-ride-toast-circling-notified",
  TOAST_CIRCLING_FAILED: "driver-app-active-ride-toast-circling-failed",
  TOAST_MARKED_ARRIVED: "driver-app-active-ride-toast-marked-arrived",
  TOAST_RIDE_STARTED: "driver-app-active-ride-toast-ride-started",
  TOAST_RIDE_COMPLETED: "driver-app-active-ride-toast-ride-completed",
  TOAST_RIDE_STOPPED: "driver-app-active-ride-toast-ride-stopped",
  TOAST_ACTION_FAILED: "driver-app-active-ride-toast-action-failed",
  TOAST_PHONE_UNAVAILABLE: "driver-app-active-ride-toast-phone-unavailable",
  TOAST_CHAT_FAILED: "driver-app-active-ride-toast-chat-failed",
  TOAST_CANCEL_FAILED: "driver-app-active-ride-toast-cancel-failed",
  TOAST_TRIP_CANCELLED: "driver-app-active-ride-toast-trip-cancelled",
  TOAST_CANCEL_TRIP_FAILED: "driver-app-active-ride-toast-cancel-trip-failed",
  TOAST_ETA_UPDATED: "driver-app-active-ride-toast-eta-updated",
  TOAST_ETA_FAILED: "driver-app-active-ride-toast-eta-failed",
  TOAST_ETA_ERROR: "driver-app-active-ride-toast-eta-error",
  CONTACT_SHEET_TITLE: "driver-app-active-ride-contact-sheet-title",
  CONTACT_PHONE_LABEL: "driver-app-active-ride-contact-phone-label",
  CONTACT_PHONE_NA: "driver-app-active-ride-contact-phone-na",
  CONTACT_CALL_CELLULAR: "driver-app-active-ride-contact-call-cellular",
  CONTACT_CHAT: "driver-app-active-ride-contact-chat",
  CONTACT_WHATSAPP: "driver-app-active-ride-contact-whatsapp",
  SOS_SHEET_TITLE: "driver-app-active-ride-sos-sheet-title",
  SOS_CALL_DISPATCH: "driver-app-active-ride-sos-call-dispatch",
  SOS_CALL_911: "driver-app-active-ride-sos-call-911",
  CANCEL_SHEET_TITLE: "driver-app-active-ride-cancel-sheet-title",
  CANCEL_SELECT_REASON_LABEL:
    "driver-app-active-ride-cancel-select-reason-label",
  CANCEL_CHOOSE_REASON: "driver-app-active-ride-cancel-choose-reason",
  CANCEL_ADD_COMMENTS_LABEL: "driver-app-active-ride-cancel-add-comments-label",
  CANCEL_COMMENTS_PLACEHOLDER:
    "driver-app-active-ride-cancel-comments-placeholder",
  CANCEL_CONTINUE: "driver-app-active-ride-cancel-continue",
  CANCEL_REASONS_SHEET_TITLE: "driver-app-active-ride-reasons-sheet-title",
  CANCEL_REASON_VEHICLE_ISSUE:
    "driver-app-active-ride-cancel-reason-vehicle-issue",
  CANCEL_REASON_CUSTOMER_NO_SHOW:
    "driver-app-active-ride-cancel-reason-customer-no-show",
  CANCEL_REASON_WRONG_ADDRESS:
    "driver-app-active-ride-cancel-reason-wrong-address",
  CANCEL_REASON_SAFETY_CONCERN:
    "driver-app-active-ride-cancel-reason-safety-concern",
  CANCEL_REASON_PERSONAL_EMERGENCY:
    "driver-app-active-ride-cancel-reason-personal-emergency",
  CANCEL_REASON_OTHER: "driver-app-active-ride-cancel-reason-other",
  CONFIRM_TITLE: "driver-app-active-ride-confirm-title",
  CONFIRM_DESCRIPTION_VEHICLE_ISSUE_PREFIX:
    "driver-app-active-ride-confirm-description-vehicle-issue-prefix",
  CONFIRM_DESCRIPTION_VEHICLE_ISSUE_SUFFIX:
    "driver-app-active-ride-confirm-description-vehicle-issue-suffix",
  CONFIRM_DESCRIPTION_DEFAULT:
    "driver-app-active-ride-confirm-description-default",
  CONFIRM_CANCEL: "driver-app-active-ride-confirm-cancel",
  CONFIRM_CONFIRM: "driver-app-active-ride-confirm-confirm",
  CONFIRM_LOADING: "driver-app-active-ride-confirm-loading",
  ETA_SHEET_TITLE: "driver-app-active-ride-eta-sheet-title",
  ETA_SHEET_DESCRIPTION: "driver-app-active-ride-eta-sheet-description",
  ETA_FETCHING: "driver-app-active-ride-eta-fetching",
  ETA_UPDATING: "driver-app-active-ride-eta-updating",
  ETA_BUTTON: "driver-app-active-ride-eta-button",
  ERROR_LOAD_TRIP: "driver-app-active-ride-error-load-trip",
  ERROR_ETA_MISSING: "driver-app-active-ride-error-eta-missing",
} as const;
