export const FEEDBACK_CONTENT_KEYS = {
  HEADER_TITLE: "driver-app-feedback-header-title",
  FARE_SUMMARY_TITLE: "driver-app-feedback-fare-summary-title",
  FARE_RIDE_PRICE: "driver-app-feedback-fare-ride-price",
  FARE_TOLLS: "driver-app-feedback-fare-tolls",
  FARE_DISCOUNT: "driver-app-feedback-fare-discount",
  FARE_UNBILLED_TOLLS: "driver-app-feedback-fare-unBilled-tolls",
  FARE_EXTRA_WAIT_TIME: "driver-app-feedback-fare-extra-wait-time",
  FARE_ADDITIONAL_STOPS: "driver-app-feedback-fare-additional-stops",
  RATING_TITLE: "driver-app-feedback-rating-title",
  RATING_QUESTION: "driver-app-feedback-rating-question",
  COMMENTS_LABEL: "driver-app-feedback-comments-label",
  COMMENTS_PLACEHOLDER: "driver-app-feedback-comments-placeholder",
  ACTION_SKIP: "driver-app-feedback-action-skip",
  ACTION_SUBMIT: "driver-app-feedback-action-submit",
  TOAST_RATING_REQUIRED: "driver-app-feedback-toast-rating-required",
  TOAST_MISSING_TRIP: "driver-app-feedback-toast-missing-trip",
  TOAST_SUCCESS: "driver-app-feedback-toast-success",
  TOAST_SUBMIT_FAILED: "driver-app-feedback-toast-submit-failed",
  TOAST_ERROR: "driver-app-feedback-toast-error",
  ERROR_FETCH_TRIP: "driver-app-feedback-error-fetch-trip",
} as const;
