export const NOTIFICATIONS_CONTENT_KEYS = {
  HEADER_TITLE: "driver-app-notifications-header-title",
  ACTION_CLEAR_ALL: "driver-app-notifications-action-clear-all",
  TAB_ALL: "driver-app-notifications-tab-all",
  TAB_UNREAD: "driver-app-notifications-tab-unread",
  TAB_READ: "driver-app-notifications-tab-read",
  LOADING_MESSAGE: "driver-app-notifications-loading-message",
  EMPTY_ALL: "driver-app-notifications-empty-all",
  EMPTY_FILTERED_PREFIX: "driver-app-notifications-empty-filtered-prefix",
  EMPTY_FILTERED_SUFFIX: "driver-app-notifications-empty-filtered-suffix",
  ALERT_REPLY_SENT_TITLE: "driver-app-notifications-alert-reply-sent-title",
  ALERT_REPLY_SENT_MESSAGE: "driver-app-notifications-alert-reply-sent-message",
  ALERT_ERROR_TITLE: "driver-app-notifications-alert-error-title",
  ALERT_REPLY_FAILED: "driver-app-notifications-alert-reply-failed",
  ALERT_OK: "driver-app-notifications-alert-ok",
  ALERT_DELETE_TITLE: "driver-app-notifications-alert-delete-title",
  ALERT_DELETE_MESSAGE: "driver-app-notifications-alert-delete-message",
  ALERT_DELETE_CANCEL: "driver-app-notifications-alert-delete-cancel",
  ALERT_DELETE_CONFIRM: "driver-app-notifications-alert-delete-confirm",
  ALERT_DELETE_FAILED: "driver-app-notifications-alert-delete-failed",
  ALERT_DELETE_ALL_TITLE: "driver-app-notifications-alert-delete-all-title",
  ALERT_DELETE_ALL_MESSAGE: "driver-app-notifications-alert-delete-all-message",
  ALERT_DELETE_ALL_CONFIRM: "driver-app-notifications-alert-delete-all-confirm",
  ALERT_DELETE_ALL_FAILED: "driver-app-notifications-alert-delete-all-failed",
} as const;
