export const PROFILE_CONTENT_KEYS = {
  HEADER_TITLE: "driver-app-profile-header-title",
  NAME_FALLBACK: "driver-app-profile-name-fallback",
  VALUE_NA: "driver-app-profile-value-na",
  SECTION_PERSONAL: "driver-app-profile-section-personal",
  SECTION_CONTACT: "driver-app-profile-section-contact",
  SECTION_DRIVER_DETAILS: "driver-app-profile-section-driver-details",
  SECTION_ACTIVITY: "driver-app-profile-section-activity",
  SECTION_PAYMENT: "driver-app-profile-section-payment",
  PERSONAL_FULL_NAME: "driver-app-profile-personal-full-name",
  PERSONAL_DATE_OF_BIRTH: "driver-app-profile-personal-date-of-birth",
  PERSONAL_GENDER: "driver-app-profile-personal-gender",
  PERSONAL_ETHNICITY: "driver-app-profile-personal-ethnicity",
  PERSONAL_LANGUAGES: "driver-app-profile-personal-languages",
  PERSONAL_YEARS_OF_EXPERIENCE:
    "driver-app-profile-personal-years-of-experience",
  CONTACT_EMAIL: "driver-app-profile-contact-email",
  CONTACT_PHONE: "driver-app-profile-contact-phone",
  CONTACT_WHATSAPP: "driver-app-profile-contact-whatsapp",
  DRIVER_NUMBER: "driver-app-profile-driver-number",
  DRIVER_ID: "driver-app-profile-driver-id",
  DRIVER_NETWORK_NUMBER: "driver-app-profile-driver-network-number",
  DRIVER_TYPE: "driver-app-profile-driver-type",
  DRIVER_AVAILABILITY: "driver-app-profile-driver-availability",
  DRIVER_GRADE: "driver-app-profile-driver-grade",
  DRIVER_CURRENT_STATUS: "driver-app-profile-driver-current-status",
  DRIVER_RIDE_STATUS: "driver-app-profile-driver-ride-status",
  STATUS_ONLINE: "driver-app-profile-status-online",
  STATUS_OFFLINE: "driver-app-profile-status-offline",
  ACTIVITY_TOTAL_RIDES: "driver-app-profile-activity-total-rides",
  ACTIVITY_LAST_ACTIVE: "driver-app-profile-activity-last-active",
  ACTIVITY_LAST_SIGN_IN: "driver-app-profile-activity-last-sign-in",
  PAYMENT_COMMISSION: "driver-app-profile-payment-commission",
  PAYMENT_HOURLY_RATE: "driver-app-profile-payment-hourly-rate",
  PAYMENT_DISTANCE_RATE: "driver-app-profile-payment-distance-rate",
  PAYMENT_CYCLE: "driver-app-profile-payment-cycle",
  PAYMENT_DAY: "driver-app-profile-payment-day",
  PAYMENT_BANK_NAME: "driver-app-profile-payment-bank-name",
  PAYMENT_ACCOUNT_NAME: "driver-app-profile-payment-account-name",
  PAYMENT_ACCOUNT_NUMBER: "driver-app-profile-payment-account-number",
  ACTION_EDIT_PORTAL: "driver-app-profile-action-edit-portal",
  NOTE_EDIT_INFO: "driver-app-profile-note-edit-info",
} as const;
