export const SETTINGS_CONTENT_KEYS = {
  HEADER_TITLE: "driver-app-settings-header-title ",
  LOADING_MESSAGE: "driver-app-settings-loading-message",
  TOAST_SAVED: "driver-app-settings-toast-saved",
  FEATURED_TITLE: "driver-app-settings-featured-title",
  FEATURED_DESCRIPTION: "driver-app-settings-featured-description",
  ETA_TITLE: "driver-app-settings-eta-title",
  ETA_DESCRIPTION: "driver-app-settings-eta-description",
  AUTO_BID_TITLE: "driver-app-settings-auto-bid-title",
  AUTO_BID_DESCRIPTION: "driver-app-settings-auto-bid-description",
  AUTO_BID_PLACEHOLDER: "driver-app-settings-auto-bid-placeholder",
  AUTO_BID_CUSTOMER_PRICE: "driver-app-settings-auto-bid-customer-price",
  SHEET_BID_PRICE_TITLE: "driver-app-settings-sheet-bid-price-title",
  BID_OPTION_PLUS_10: "driver-app-settings-bid-option-plus-10",
  BID_OPTION_PLUS_5: "driver-app-settings-bid-option-plus-5",
  BID_OPTION_CUSTOMER_PRICE: "driver-app-settings-bid-option-customer-price",
  BID_OPTION_MINUS_5: "driver-app-settings-bid-option-minus-5",
  BID_OPTION_MINUS_10: "driver-app-settings-bid-option-minus-10",
  ACTION_SAVE: "driver-app-settings-action-save",
} as const;
